{% set name = "MAPIE" %}
{% set version = "0.4.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0]|lower }}/{{ name|lower }}/{{ name }}-{{ version }}.tar.gz
  sha256: b816ed79a3f2be419926199bbd490dd79a9a74c434d467c8f9bc271b2dee8121

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - numpy >=1.21
    - packaging
    - python >=3.7
    - scikit-learn

test:
  imports:
    - mapie
    - mapie.tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/MAPIE/
  summary: A scikit-learn-compatible module for estimating prediction intervals.
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://mapie.readthedocs.io/en/latest/
  dev_url: https://github.com/scikit-learn-contrib/MAPIE

extra:
  recipe-maintainers:
    - gmartinonQM
    - vtaquet
    - vincentblot28
