{% set name = "MAPIE" %}
{% set version = "0.8.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0]|lower }}/{{ name|lower }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1d34bc5c4a43550d8255fa8a75d0168ea3d6523388d5dbddfc5d3c65a8b6b6a0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - numpy >=1.21
    - packaging
    - python >=3.7
    - scikit-learn

test:
  imports:
    - mapie
    - mapie.tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/MAPIE/
  summary: A scikit-learn-compatible module for estimating prediction intervals.
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://mapie.readthedocs.io/en/latest/
  dev_url: https://github.com/scikit-learn-contrib/MAPIE

extra:
  recipe-maintainers:
    - thibaultcordier
    - tmorzade
    - LacombeLouis
    - gmartinonQM
    - vtaquet
    - vincentblot28
